[package]
name = "alfangodb"
version = "1.0"
description = "Database for the Internet Computer"
repository = "https://github.com/sagcryptoicp/alfangodb"
license = "MIT"

[dependencies]
base = "0.11.1"
rand = "https://github.com/aviate-labs/rand.mo#v0.2.3"
ulid = "https://github.com/aviate-labs/ulid.mo#v0.1.3"
map = "https://github.com/ZhenyaUsenko/motoko-hash-map#v9.0.1"